[package]
name = "libevdev-bindgen"
version = "0.1.0"
authors = ["Brendan"]
edition = "2018"
links = "evdev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.51.0"
pkg-config = "0.3.16"
